### ISSUE TITLE
Element send_keys can't send '@'

### ISSUE THREAD

**Issue by DimitriTimoz** [jonhoo/fantoccini#159] opened 2022-02-14 22:37 UTC
When we call the method send_keys on a element with a &str which contain an '@' we get the following error:
`Standard(WebDriver { error: UnknownError, message: "unknown error: Cannot construct KeyEvent from non-typeable key\n })`
Here is my code if I did a mistake:
```rust
 client
        .wait()
        .for_element(Locator::Css("input[name='email']"))
        .await?
        .send_keys("email@example.com").await?;
```
I'have tried with a &str without a '@' and it worked

**Comment by jonhoo** [comment] 2022-02-19 18:23
@stevepryde Do you know what might cause this? Sounds like some kind of escaping issue.

**Comment by stevepryde** [comment] 2022-02-19 21:51
I haven't seen this before. I'll have a look because I'm curious about what's happening here.

**Comment by stevepryde** [comment] 2022-02-19 22:51
I modified one of the examples to test this and this works fine for me:
```rust
    client.goto("https://play.rust-lang.org/").await?;
    let code_area = client
        .wait()
        .for_element(Locator::Css(".ace_text-input"))
        .await?;

    code_area.send_keys("email@example.com").await?;
```

Could it be something else like a version mismatch between geckodriver & Firefox (or chromedriver & Chrome) ?

@DimitriTimoz could you please post the browser you're using and the browser + webdriver versions? Thanks

**Comment by jonhoo** [comment] 2024-01-06 12:27
I'm going to close this as can't-produce. Feel free to open if you have updated reproduction steps!

**Closed by jonhoo** 2024-01-06 12:27 UTC
