### ISSUE TITLE
Are explicit `drop`s necessary?

### ISSUE THREAD

**Issue by Phrohdoh** [jonhoo/fantoccini#5] opened 2018-01-04 19:35 UTC
Writing explicit `drop` invocations is pretty counter-intuitive.

Is the `fin` function in your examples performing cleanup that is only possible if `c` has been dropped?

**Comment by jonhoo** [comment] 2018-01-05 09:47
I agree with you that having to call `drop` explicitly is pretty unfortunate. The reason it is currently needed is to avoid swallowing any errors. I *could* have the implementation of `Drop` resolve the `fin` future internally, which would in turn mean you can just let `Client` fall out of scope as normal, but this would also mean that if any errors occur when tearing down the connection, that error would either be hidden from the user, or cause a panic (if `drop` calls `unwrap`).

For what it's worth, the reason that `Client` has to be explicitly dropped is that it internally contains a reference-counted [`Inner`](https://github.com/jonhoo/fantoccini/blob/master/src/lib.rs#L213) (This is what allows `Client` to be `Clone`). Only when the last `Client` is dropped will `Inner`'s [destructor](https://github.com/jonhoo/fantoccini/blob/master/src/lib.rs#L255) be called (which calls [`shutdown`](https://github.com/jonhoo/fantoccini/blob/master/src/lib.rs#L224)). If `shutdown` isn't called, then a) the WebDriver session isn't terminated, and b) `fin` would never resolve.

**Comment by jonhoo** [comment] 2018-01-06 15:40
Pushed a proposed change in bd4c9d1 — how does that look to you?
See in particular:
https://github.com/jonhoo/fantoccini/blob/master/src/lib.rs#L362-L367
and
https://github.com/jonhoo/fantoccini/blob/master/src/lib.rs#L757-L770
As well as the updated examples in the README.

**Comment by Phrohdoh** [comment] 2018-01-06 17:01
This is definitely a usage improvement!

Is there machinery that prevents the `close` future from being driven to completion (thus ending the session) before the actual work is completed?

**Comment by jonhoo** [comment] 2018-01-06 17:09
> This is definitely a usage improvement!

Great!

> Is there machinery that prevents the `fin` future from being driven to completion (thus ending the session) before the actual work is completed?

Hmm, I'm not entirely sure what you mean here. I *think* what you're asking is why fantoccini can't just internally run the `fin` future to completion, and thus do the cleanup for the user? If so, the answer is that the library only has a `Handle` to the Tokio [`Core`](https://tokio-rs.github.io/tokio-core/tokio_core/reactor/struct.Core.html) used to drive the HTTP connection to the WebDriver server. It can schedule work for that core using the handle, but it can't actually execute that work. Therefore, it becomes up to the caller (who has the `Core`) to use `core.run()` to complete the request. The library also cannot just create a *new* `Core` for doing cleanup, because the `hyper::Client` is already tied to the user's original `Handle`:
https://github.com/jonhoo/fantoccini/blob/599892442bd139ef9ad01e2176b25048cfdd990a/src/lib.rs#L382-L384

**Comment by Phrohdoh** [comment] 2018-01-06 17:19
Sorry I was not very clear.

I meant "are we sure that the cleanup future won't execute until after all of the *actual work** is done?"

**Comment by jonhoo** [comment] 2018-01-06 23:04
Ah, I see. Technically, no. I don't think tokio/hyper gives guarantees about the order in which futures/requests are resolved. Given that they're all asynchronous, I suppose theoretically some existing WebDriver request could be lying around somewhere, not yet written to the wire,  and then the shutdown command could be spawned on the core and race ahead of the existing command. But this sounds pretty unlikely to occur in practice to me. it's also not clear that we have a way to guard against this internally in the library, since we have no control over the execution of the futures that we return.

**Closed** 2018-01-07 05:10 UTC

**Comment by jonhoo** [comment] 2018-01-07 09:54
Publishing this now as 0.8.0, but open to further suggestions for how to improve the API :)

**Comment by ababo** [comment] 2020-02-07 16:19
@jonhoo Still didn't get is there a way to make Client to close when exiting its scope?

**Comment by jonhoo** [comment] 2020-02-07 18:15
No, sadly there is no such way since when a `Client` is dropped it is not able to execute any asynchronous code. We _could_ perhaps check if there was still an active runtime, and if so, spawn the destructor, but that's itself pretty error-prone, and could result in some weird unexpected behavior. What we really want are [Asynchronous Destructors](https://boats.gitlab.io/blog/post/poll-drop/), but those don't seem like they're going to be here any time soon.
