### ISSUE TITLE
Bug: Search element from element does not start search from there

### ISSUE THREAD

**Issue by lcmgh** [jonhoo/fantoccini#168] opened 2022-04-08 16:18 UTC
fantoccini = "0.18.0"

```rust
let contracts_xpath = r#"//Table[contains(concat(" ", normalize-space(@aria-label), " "), "Region = Contracts")]//*[contains(concat(" ", normalize-space(@headers), " "), "ID")]/a/../.."#;
let contract_rows = client.find_all(Locator::XPath(contracts_xpath)).await?;

for row in contract_rows.iter_mut() {

    info!("debug: {:?}", row.html(false).await.unwrap());
    let mut contracts_ahref: Vec<Element> = vec![];
    // Find Link within descendant elements
    let mut a = row
        .find(Locator::XPath(
            r#"//*[contains(concat(" ", normalize-space(@headers), " "), "ID")]/a"#,
        ))
        .await
        .unwrap();

     info!("a {}", a.html(false).await.unwrap()); # Returns code that was not printed before
}
```

Looks like the search is not starting from the element.

**Comment by stevepryde** [comment] 2022-04-10 06:38
I've encountered this exact thing before. It's not a bug. This is an artifact of how XPath works.
To do a relative search from an element with XPath, you have to start with a dot (`.`).

So in your case, it should start with `.//` etc. An XPath starting with `/` will always search from the root element regardless.

You will see exactly the same behaviour if you use the python selenium client and I would assume others too.

**Comment by jonhoo** [comment] 2022-04-10 18:56
Thanks for the clarification @stevepryde! In that case I'll go ahead and close this one.

**Closed by jonhoo** 2022-04-10 18:56 UTC

**Comment by lcmgh** [comment] 2022-04-11 07:13
I migrated to thirtyfour just to end up with exactly the same issue lol. Thanks for clarifying @stevepryde. @jonhoo I think that should be noted somewhere. If not in the docs then in the examples.
